### PR TITLE
Update TP3 to solve na error

### PR DESCRIPTION
**Pull request by dvdvideo1234**
```
[Trakpak3] lua/entities/tp3_signal_master.lua:404: attempt to index field 'paths' (a nil value)
  1. SetPathState - lua/entities/tp3_signal_master.lua:404
   2. EvaluateLogic - lua/trakpak3/pathconfig.lua:86
    3. v - lua/trakpak3/pathconfig.lua:95
     4. Run - lua/includes/modules/hook.lua:84
      5. unknown - lua/entities/tp3_switch_lever_anim.lua:101
       6. CleanUpMap - [C]:-1
        7. unknown - lua/includes/modules/cleanup.lua:170
         8. unknown - lua/includes/modules/concommand.lua:54 (x36)
```

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Also maybe something similar is needed for
```
[Trakpak3] lua/entities/tp3_switch.lua:570: attempt to call method 'ScanTrigger' (a nil value)
  1. v - lua/entities/tp3_switch.lua:570
   2. unknown - lua/includes/modules/hook.lua:84 (x352)
```

**Comment by MagnumMacKivler** [comment]
Will check this out tomorrow.

**Comment by MagnumMacKivler** [comment]
Sorry for the delay, I was busy for a few days.

Is this what you did:

1. In tp3_signal_master ENT:SetPathState(), you put the contents of the function inside an `if self.paths then` statement.
2. In tp3_switch, you moved ENT:ScanTrigger() to be defined before the Think hook is added.

If this is what you meant to do then it looks ok to me.

**Comment by dvdvideo1234** [comment]
@MagnumMacKivler 

Yes, that is correct. ;)

**Pull request merged**
